### ISSUE TITLE
Error when building project depending on iron-llvm

### ISSUE THREAD

**Issue by hawkw** [jauhien/iron-llvm#1]
I've been working with the `librustc` LLVM bindings directly in a project, and have started attempting to rewrite the project to use `iron-llvm` instead. However, when I add `iron-llvm` to the `Cargo.toml` dependencies as described in the README, I get the following error on builds:

``` bash
$ cargo build
    Updating git repository `https://github.com/jauhien/iron-llvm.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling bitflags v0.3.2
   Compiling semver v0.1.20
   Compiling gcc v0.3.18
   Compiling llvm-sys v0.2.1
   Compiling cmake v0.1.7
   Compiling iron_llvm v0.0.1 (https://github.com/jauhien/iron-llvm.git#7db73d72)
Build failed, waiting for other jobs to finish...
failed to run custom build command for `llvm-sys v0.2.1`
Process didn't exit successfully: `/Users/hawk/Development/mnemosyne/target/debug/build/llvm-sys-9bcc4041ad5d7b40/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Couldn't execute llvm-config. Error: No such file or directory (os error 2)', /Users/hawk/.cargo/registry/src/github.com-0a35038f75765ae4/llvm-sys-0.2.1/build.rs:13
```

**Comment by jauhien** [comment]
That's something llvm-sys related. I'll have a look.

**Comment by jauhien** [comment]
Ah, moment. Do you have llvm installed? If you're using something binary-based, you need the dev version of the package.

**Comment by jauhien** [comment]
Your build worked with rustc, as rust has bundled LLVM.

**Comment by hawkw** [comment]
Ah, I see. I assumed `llvm-sys` bundled LLVM. Sorry, that's my fault.

**Comment by hawkw** [comment]
I do have LLVM installed locally (`usr/local/opt/llvm`), but it appears that `llvm-sys` cannot find it. Is there some configuration change I need to make so that it'll build?

**Comment by jauhien** [comment]
You probably have it installed wrongly. You need to have `llvm-config` command in the `PATH`. You'd better use LLVM provided by your distribution, not something you compile and install to `/usr/local`. If you want to compile LLVM yourself you need to make sure that its binaries are in `PATH` and libraries in `LD_LIBRARY_PATH`.

**Comment by hawkw** [comment]
Ah, the issue is that on OSX, LLVM is installed by default to `/usr/local/opt/llvm`, but the `/usr/local/opt/llvm/bin/` directory (containing `llvm-config`) is not on the PATH by default. Adding that dir to the PATH fixes the issue.

**Comment by jauhien** [comment]
Ok, closing then.
