### ISSUE TITLE
Linker error in `cargo test`

### ISSUE THREAD

**Issue by hawkw** [jauhien/iron-llvm#2]
I'm not sure if this is an `iron-llvm` or `llvm-sys` issue, but I figured I'd ask here. I've got my crate building successfully, but when I run `$ cargo test`, all my tests fail with `error: linking with`cc`failed: exit code: 1`.  

It dumps the complete list of arguments and then the following: 

``` bash
note: ld: warning: directory not found for option '-L/Users/hawk/Development/mnemosyne/core/.rust/lib/x86_64-apple-darwin'
ld: warning: directory not found for option '-L/Users/hawk/Development/mnemosyne/core/lib/x86_64-apple-darwin'
ld: library not found for -lLLVMLTO
```

I'd be happy to post the whole error message, but it's rather long. I have this issue both locally on my Macbook and on Travis (running Ubuntu 12.04) and I can provide any other system configuration information if necessary.

 It's entirely possible that this is completely my fault, in which case, sorry for opening so many bug reports, but any help would be greatly appreciated.

**Comment by jauhien** [comment]
Do you have your code somewhere where I could look at it?

> It's entirely possible that this is completely my fault, in which case, sorry for opening so many bug reports, but any help would be greatly appreciated.

No problem, I'm glad to have users of this lib. ) But note, that until it is released on cargo.io (beginning of the next year, I think) it is completely unstable and can break APIs with every commit.

**Comment by hawkw** [comment]
All the code is in my repository [here](https://github.com/hawkw/mnemosyne). Here's the first [travis build](https://travis-ci.org/hawkw/mnemosyne/jobs/86655395#L6038) that failed due to this issue, if you want to check that out.

**Comment by jauhien** [comment]
Thanks, I'll have a look.

**Comment by hawkw** [comment]
Do let me know if there's any additional information you need.

**Comment by hawkw** [comment]
Okay, I figured this one out on my own, actually, and in retrospect, the solution was painfully obvious: all of my tests were written as doctests, which Cargo treats as their own separate crate. Therefore, it doesn't run the build script and link in LLVM before running the tests. If the tests are in test modules within the main crate, everything is fine. 

I suppose there probably ought to be a note in the docs that tests written as doctests will fail?

**Comment by jauhien** [comment]
@hawkw: thanks, I'll write a note about it later.

Also building of your project with the latest nightly rust failed for me (on one of deps it seems).

If you'll have any issues, please, fill free to post them here or send a pull request, but note, that I'm on journey until 09.11, so i probably will be not able to answer.

**Comment by hawkw** [comment]
Huh, it works on my machine, and on Travis (against nightly). Which dependency is causing problems?

**Comment by jauhien** [comment]
I have this error:

```
jauhien@calculate mnemosyne % cargo build
 Downloading itertools v0.4.2
 Downloading clap v1.4.5
 Downloading combine v1.0.2
   Compiling combine v1.0.2
   Compiling libc v0.1.10
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/combine-1.0.2/src/lib.rs:1:1: 1:1 error: can't find crate for `std` [E0463]
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/combine-1.0.2/src/lib.rs:1 //! This crate contains parser combinators, roughly based on the Haskell library [parsec](http://hackage.haskell.org/package/parsec).
                                                                                         ^
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/libc-0.1.10/rust/src/liblibc/lib.rs:1:1: 1:1 error: can't find crate for `std` [E0463]                                                                          
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/libc-0.1.10/rust/src/liblibc/lib.rs:1 // Copyright 2012-2015 The Rust Project Developers. See the COPYRIGHT
                                                                                                    ^
error: aborting due to previous error
Could not compile `combine`.
                                                                                                               
To learn more, run the command again with --verbose.
jauhien@calculate mnemosyne % cargo build --verbose
   Compiling mnemosyne v0.1.0 (file:///home/jauhien/data/work/rust/mnemosyne)
     Running `rustc core/build.rs --crate-name build_script_build --crate-type bin -g --out-dir /home/jauhien/data/work/rust/mnemosyne/target/debug/build/mnemosyne-71b3b9a373766fb3 --emit=dep-info,link -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps`
   Compiling strsim v0.4.0
     Running `rustc /home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/strsim-0.4.0/src/lib.rs --crate-name strsim --crate-type lib -g -C metadata=2b2577dcbd7870f8 -C extra-filename=-2b2577dcbd7870f8 --out-dir /home/jauhien/data/work/rust/mnemosyne/target/debug/deps --emit=dep-info,link -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps --cap-lints allow`
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/strsim-0.4.0/src/lib.rs:1:1: 1:1 error: can't find crate for `std` [E0463]
/home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/strsim-0.4.0/src/lib.rs:1 
                                                                                        ^
error: aborting due to previous error
core/build.rs:1:1: 1:1 error: can't find crate for `std` [E0463]
core/build.rs:1 // build.rs
                ^
error: aborting due to previous errorBuild failed, waiting for other jobs to finish...
                                                                                                               
Could not compile `strsim`.                                                                                    
                                                                                                               
Caused by:
  Process didn't exit successfully: `rustc /home/jauhien/.cargo/registry/src/github.com-121aea75f9ef2ce2/strsim-0.4.0/src/lib.rs --crate-name strsim --crate-type lib -g -C metadata=2b2577dcbd7870f8 -C extra-filename=-2b2577dcbd7870f8 --out-dir /home/jauhien/data/work/rust/mnemosyne/target/debug/deps --emit=dep-info,link -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps -L dependency=/home/jauhien/data/work/rust/mnemosyne/target/debug/deps --cap-lints allow` (exit code: 101)
```

**Comment by jauhien** [comment]
Also may be something bad with my local configuration. I'll return to this later.

**Comment by jauhien** [comment]
Do not mind, I have something broken locally. Your project has nothing to do with it.

**Comment by Hywan** [comment]
@hawkw @jauhien Is there any solution to make doctest work? I have the same issue on my project (based on `llvm-sys`, not `iron-llvm`).
